/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --chr 4 --start 81000000 --end 83000000 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs12570944 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs9667489 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs10036789 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs138650617 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs2738265 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs12950511 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --chr 2 --start 172400000 --end 173100000 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs13118211 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs7744813 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs10887262 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs36090025 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --chr 14 --start 60600000 --end 61300000 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs9330814 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs41393947 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs12193446 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs10824539 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs3138142 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs7184522 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs7405453 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs2573222 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs72644322 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs10089517 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs2472493 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs1367024 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs3750846 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs11606250 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs5442 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --chr 13 --start 100500000 --end 100900000 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs524952 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
/share/pub/xuezb/software/locuszoom/bin/locuszoom --metal /share/pub/xuezb/biobank/GWAS/ASSET/UKB_v1/Meta.txt --refsnp rs11631829 --markercol SNP --pvalcol P --build hg19 --pop EUR --source 1000G_Nov2014 --cache None
